-- Fixes a pre-existing, dangerous column default: `is_admin` defaulted
-- to `true`, not `false` (visible via information_schema — this
-- predates the migrations folder, presumably set by hand in the
-- Supabase SQL editor). handle_new_user() (the on_auth_user_created
-- trigger) inserts a profiles row with only (id, full_name), relying
-- entirely on this default for is_admin — so every new signup was
-- implicitly an admin candidate.
--
-- That was silently harmless only until a real single-admin constraint
-- existed to enforce against it. Now that one does
-- (profiles_single_admin_uq, added in 20260914000000), a second row
-- landing with is_admin/admin_flag = true immediately collides with the
-- existing ADMIN's row, and the whole INSERT — and with it,
-- auth.admin.createUser() itself, since the trigger runs in the same
-- transaction — fails with "Database error creating new user". In
-- effect, creating any new account (Settings -> Users & Access -> Add a
-- user) was broken the moment this project got its first ADMIN.
alter table public.profiles alter column is_admin set default false;
